services:
  db:
    image: postgres:15
    container_name: postgres-shop
    restart: always
    ports:
      - "5433:5432"  # use another port(5433) because i have local db with port 5432
    environment:
      POSTGRES_DB: justshop
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shop123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
