version: "3.9"

services:
  db:
    image: postgres:15
    container_name: shop_pgsql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: justshop
      POSTGRES_USER: justshop
      POSTGRES_PASSWORD: justshop
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
